```yaml
# Configurer l'environnement
addons:
apt:
packages:
- python3
- python3-pip

install:
- pip install -r requirements.txt

# Exécuter les tests unitaires
script:
- pytest tests/

# Exécuter les notebooks de tests
- jupyter nbconvert --to script tests/notebooks
- python test_notebooks.py

# Reporter les résultats
after_success:
- codecov # Intégrer Codecov pour rapport de couverture
- coveralls # ou Coveralls

# Valider les PRs
jobs:
include:
- stage: validations
if: type = pull_request
script:
- pytest tests/
- jupyter nbconvert --to script tests/notebooks
- python test_notebooks.py
```